name: Frontend CI/CD pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: Build and push docker image to ECR
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurationj AWS Creds
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{secrets.AWS_REGION}}

      # ECR Login
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -f videostream-frontend/Dockerfile -t ${{secrets.ECR_REPOSITORY}}:${{github.sha}} videostream-frontend          

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag ${{secrets.ECR_REPOSITORY}}:${{github.sha}} \
          ${{secrets.AWS_ACCOUNT}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/${{secrets.ECR_REPOSITORY}}:${{github.sha}}

      # Push Docker Image to ECR
      - name: Push Docker Image to ECR
        run: |
          docker push ${{secrets.AWS_ACCOUNT}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/${{secrets.ECR_REPOSITORY}}:${{github.sha}}